general {
    lock_cmd = hyprlock          # what to run when idle timeout hits
    before_sleep_cmd = hyprlock  # lock before system sleeps
    after_sleep_cmd = echo "woke up"
}

listener {
    timeout = 300                # seconds (300s = 5 minutes)
    on-timeout = hyprlock        # run when idle for 5min
    on-resume = echo "back"      # when user comes back
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}
