general {
    lock_cmd = omarchy-system-lock
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = sleep 1 && omarchy-system-wake # to avoid having to press a key twice to turn on the display.
    inhibit_sleep = 3
}


listener {
    timeout = 150                                 # 5min
    on-timeout = pidof hyprlock || omarchy-launch-screensaver
}

listener {
    timeout = 900
    on-timeout = omarchy-system-lock
    on-resume = omarchy-system-wake

    # on-timeout = hyprctl dispatch dpms off                            # screen off when timeout has passed
    # on-resume = hyprctl dispatch dpms on && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

