if-shell 'tmux display-message -p "#{session_name}" 2>/dev/null' \
  'bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded ✅"'
# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
set mouse on 
# status bar on top
set-option -g status-position top
# Vim motions 
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
## Maximize 
bind -r m resize-pane -Z
set -ga terminal-overrides ",*256col*:Tc"
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# Windows and panes start at 1
set -g base-index 1
setw -g pane-base-index 1

setw -g clock-mode-colour '#bd93f9'
setw -g mode-style 'fg=#ff5555 bg=#44475a bold'
set -g pane-border-style 'fg=#44475a bg=#282a36'
set -g pane-active-border-style 'fg=#bd93f9 bg=#282a36'

# statusbar
set -g status-justify left
set -g status-style 'bg=#44475a fg=#f8f8f2 bold'
set -g status-interval 2
set -g status-left ''
set -g status-right '#{prefix_highlight} #[fg=#282a36,bg=#6272a4,bold] %d/%m #[fg=#282a36,bg=#f8f8f2,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=#ffb86c bg=#44475a bold'
setw -g window-status-current-format ' #I#[fg=#f8f8f2]:#[fg=#ffffff]#W#[fg=#f1fa8c]#F '
setw -g window-status-style 'fg=#6272a4 bg=#282a36 none'
setw -g window-status-format ' #I#[fg=#44475a]:#[fg=#6272a4]#W#[fg=#6272a4]#F '
setw -g window-status-bell-style 'fg=#f8f8f2 bg=#ff5555 bold'

##### Messages
set -g message-style 'fg=#282a36 bg=#ffb86c bold'
set -g message-command-style 'fg=#8be9fd bg=#282a36'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
#set -g @plugin 'mattdavis90/base16-tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
# set desired theme options...
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
# Prefix Highlight colors (styling)
set -g @prefix_highlight_fg 'black'
set -g @prefix_highlight_bg 'yellow,bold'
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_copy_mode_attr 'fg=black,bg=yellow,bold'
# Base16 theme selection
#set -g @colors-base16 'gruvbox-dark-hard'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
